Assignment_A02
Priyanka15-12/Traning pull request #1
Opened 2023-07-26 06:45 UTC by Priyanka15-12

2023-07-28 12:18 UTC, Priyanka15-12 commented
@MetaNaveen  Pushed code.

2023-07-28 12:29 UTC, MetaNaveen requested changes
Good. It's almost done. Just fewer changes before going into next exercise.

2023-07-28 12:29 UTC, MetaNaveen commented on Program.cs
> +      int n = r.Next (a, z);
You could make z = 100 and use z + 1 since you are referencing z in other output statements.

2023-07-28 12:29 UTC, MetaNaveen commented on Program.cs
> +               Console.WriteLine ("Enter the number within the range.");
you should "continue" to skip the remaining statements as those will also be executed if the number is not in the range.

2023-07-28 12:29 UTC, MetaNaveen commented on Program.cs
> +      int a = 1;
You could combine multiple variable declarations of same data type like "int a = 1, z = 101;"

2023-07-31 12:16 UTC, merged

2023-08-01 10:56 UTC, MetaNaveen commented
Reopen.

2023-08-01 10:57 UTC, Priyanka15-12 commented
.