T10- Reverse a given number.
Priyanka15-12/Traning pull request #14
Opened 2023-08-18 08:53 UTC by Priyanka15-12

2023-08-21 19:43 UTC, MetaNaveen requested changes

2023-08-21 19:43 UTC, MetaNaveen commented on Program.cs
> +            int rem = a % 10;
rem is used only once. So could be used directly in the expression statement.

2023-08-21 19:43 UTC, MetaNaveen commented on Program.cs
> +            a = a / 10;
shorthand could be used. a /= 10;

2023-08-21 19:43 UTC, MetaNaveen commented on Program.cs
> +            Console.WriteLine ($"{num} is not a palindrome number.");
Why curly braces for single line statments? That too, for 'if' but not for 'else'?

2023-09-04 09:59 UTC, MetaNaveen commented
Working as expected.

**Final Notes:**
Minor formatting issues.

2023-09-04 09:59 UTC, closed without merging

2023-09-08 09:38 UTC, Priyanka15-12 commented
Formatting issue fixed.