T11- Digital root of a number.
Priyanka15-12/Traning pull request #16
Opened 2023-08-18 11:37 UTC by Priyanka15-12

2023-08-21 19:47 UTC, MetaNaveen requested changes

2023-08-21 19:47 UTC, MetaNaveen commented on Program.cs
> +         int quo, rem ;
space not required before semi colon.

2023-08-21 19:47 UTC, MetaNaveen commented on Program.cs
> +               rem = n % 10;
These 2 lines could be used directly in the next 2 lines.

2023-09-04 09:59 UTC, MetaNaveen approved these changes

2023-09-04 10:02 UTC, MetaNaveen commented
Working as expected.

**Final Notes:**
Should have prompted for "positive" numbers.

2023-09-04 10:02 UTC, closed without merging

2023-09-08 09:55 UTC, Priyanka15-12 commented
Modified