T18 - Armstrong number.
Priyanka15-12/Traning pull request #23
Opened 2023-08-30 04:49 UTC by Priyanka15-12

2023-09-04 11:07 UTC, MetaNaveen commented
Can you assign it your current Mentor as both 18 and 18.1 are kind of similar, and I have not yet attended the PR.?

2023-09-04 13:28 UTC, meenashriTMM commented on Program.cs
> +         Console.Write ($"{n} is a {(armstrong (n) == temp ? "" : "in")}valid armstrong number.");
'I' should be capital in 'Invalid'

2023-09-04 13:28 UTC, meenashriTMM commented on Program.cs
> +      static int armstrong (int n) {
Method name should always start with capital letter

2023-09-04 13:28 UTC, meenashriTMM commented on Program.cs
> +      static int armstrong (int n) {
Leave an empty line before method

2023-09-04 13:30 UTC, meenashriTMM commented on Program.cs
> +         int sum = 0, intlen = n.ToString ().Length;
Please follow CamelCase naming convention. i.e variable name should be intLen

2023-09-05 06:47 UTC, meenashriTMM requested changes
Formatting is incorrect

2023-09-05 07:29 UTC, meenashriTMM commented
@Priyanka15-12  Fix the review changes and then assign me.

2023-09-05 08:44 UTC, meenashriTMM approved these changes

2023-09-05 08:44 UTC, closed without merging