T23 - Voting Contest
Priyanka15-12/Traning pull request #28
Opened 2023-10-05 08:55 UTC by Priyanka15-12

2023-10-08 13:08 UTC, asfar-nazar commented on Program.cs
> +               (int, char) list = (count, c);
Why is this variable called a list ? Try to use appropriate names for variables

2023-10-08 13:09 UTC, asfar-nazar commented on Program.cs
> +         return (voteCount.MaxBy (x => x.Item1).Item2, voteCount.MaxBy (x => x.Item1).Item1);
Try to use tuples with named elements

2023-10-11 05:53 UTC, asfar-nazar requested changes

2023-10-11 05:53 UTC, asfar-nazar commented on Program.cs
> +         return (voteCount.MaxBy (x => x.Score).Candidate, voteCount.MaxBy (x => x.Score).Score);
```suggestion
         var winner = voteCount.MaxBy (x => x.Score);
         return (winner.Candidate, winner.Score);
```

2023-10-11 06:48 UTC, Priyanka15-12 commented on Program.cs
> +         return (voteCount.MaxBy (x => x.Score).Candidate, voteCount.MaxBy (x => x.Score).Score);
Changed

2023-10-11 10:41 UTC, asfar-nazar approved these changes

2023-10-11 10:41 UTC, closed without merging